name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11", "3.12" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system packages for Tk and audio backends
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-tk \
            xvfb \
            libportaudio2 \
            libsndfile1

      - name: Set up uv
        uses: astral-sh/setup-uv@v3

      - name: Install Python with uv (matrix)
        run: uv python install ${{ matrix.python-version }}

      - name: Create venv and sync dependencies
        run: |
          uv venv --python ${{ matrix.python-version }}
          uv sync --dev

      - name: Run tests under Xvfb for Tkinter
        run: |
          xvfb-run -a uv run pytest -q

